### ISSUE TITLE
Bug: trees in frozen ocean

### ISSUE THREAD

**Issue by slavalamp** [arthomnix/spaghettitrees#3]
This mod generates oaks on ice spikes in (at least) deep froze ocean for some reason.
Quilt, 1.19, seed: 4934733024993547037
with mod:
![2022-07-22_13 36 28](https://user-images.githubusercontent.com/53832230/180434522-9e9ad5c9-ae2f-4ba8-a6e1-40ddea362e13.png)
with no mod:
![2022-07-22_13 37 06](https://user-images.githubusercontent.com/53832230/180434506-08412ec8-8024-4c29-bd98-b6fff82ab414.png)

Not Enough Crashes shows this error when the game is launched, idk if that's related:
```
[14:04:38] [main/ERROR]: Failed to load config 'class dev.arthomnix.spaghettitrees.config.SpaghettiTreesConfig', using default!
me.shedaniel.autoconfig.ConfigData$ValidationException: Invalid trunk placer settings!
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at dev.arthomnix.spaghettitrees.config.SpaghettiTreesConfig.validatePostLoad(SpaghettiTreesConfig.java:77) ~[spaghettitrees-1.3.0+1.19.jar:?]
	at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:106) ~[cloth-config-7.0.73-fabric.jar:?]
	at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[cloth-config-7.0.73-fabric.jar:?]
	at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-7.0.73-fabric.jar:?]
	at dev.arthomnix.spaghettitrees.tree.feature.BetterTreesConfiguredFeatures.<clinit>(BetterTreesConfiguredFeatures.java:40) ~[spaghettitrees-1.3.0+1.19.jar:?]
	at dev.arthomnix.spaghettitrees.tree.feature.BetterTreesPlacedFeatures.<clinit>(BetterTreesPlacedFeatures.java:17) ~[spaghettitrees-1.3.0+1.19.jar:?]
	at net.minecraft.world.gen.feature.DefaultBiomeFeatures.redirect$cee000$addBetterPlainsTrees(DefaultBiomeFeatures:582) ~[?:?]
	at net.minecraft.world.gen.feature.DefaultBiomeFeatures.addPlainsFeatures(DefaultBiomeFeatures:257) ~[?:?]
	at net.minecraft.world.biome.OverworldBiomeCreator.createPlains(OverworldBiomeCreator:238) ~[?:?]
	at net.minecraft.world.biome.BuiltinBiomes.getDefaultBiome(BuiltinBiomes:12) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:154) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
```

**Comment by arthomnix** [comment]
Fixed in 1.3.1.

The error is unrelated and just means you have entered invalid config values in one of the trunk placer settings, so it is loading the default config. You can delete the config file (.minecraft/config/spaghettitrees.json) to regenerate a valid config (this will delete anything you have changed), or edit the config file manually to change the values to be valid.
For a valid trunk placer configuration:
* base height, both random heights and branch length modifiers must be positive or zero
* branch probability modifier must be between 0 and 1 inclusive
* sub branch probability divisor must be non-zero
* biases must be between 0 and 1 inclusive, and the minimum bias must be less than or equal to the maximum bias
